llm-bitsandbytes-qlora cn done
huggingface-cn/hf-blog-translation pull request #19
Opened 2023-06-14 09:48 UTC by nuass

@zhongdongy , pls help review, thx.

2023-06-14 17:03 UTC, zhongdongy requested changes
Please update and submit a revised translation. For details, please check out the comments in this PR.

2023-06-15 01:37 UTC, nuass commented on zh/llm-bitsandbytes-qlora.md
Thank you for your detailed review. I will revise it accordingly. It is obvious that many of the problems are caused by my failure to follow the original text's markdown format.

2023-07-01 11:23 UTC, zhongdongy commented
@nuass Any updates to this PR? 🤗

2023-07-01 22:57 UTC, nuass commented
@zhongdongy I don't have enough time to complete this work in the last month. If you can, please temporarily close this pr. Sorry for the delay.

2023-07-03 00:27 UTC, closed without merging